go env -u GO111MODULE GOARCH GOBIN GOCACHE GOEXPERIMENT GOFLAGS GOINSECURE GOMODCACHE GONOPROXY GONOSUMDB GOOS GOPATH GOPRIVATE GOPROXY GOROOT GOSUMDB GOTMPDIR GOVCS GCCGO AR CC CXX CGO_ENABLED CGO_CFLAGS CGO_CXXFLAGS CGO_FFLAGS CGO_LDFLAGS PKG_CONFIG 
Write-Host "Done!"
